/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Person } from "./Person";
export * as factories from "./factories";
export { Person__factory } from "./factories/Person__factory";
